repos:

    -   repo: https://github.com/ambv/black
        rev: 21.6b0
        hooks:
            - id: black
              args: [--target-version=py39, --line-length=120]
              language_version: python3.9

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.902
        hooks:
            - id: mypy
              args: [--no-strict-optional, --ignore-missing-imports, --show-error-codes]
              additional_dependencies: [types-click]

    -   repo: https://github.com/pre-commit/mirrors-pylint
        rev: v3.0.0a3
        hooks:
            - id: pylint
              args: [
                  --max-line-length=120,
                  --disable=design,
                  --disable=missing-docstring,
                  --disable=bad-continuation,
                  --disable=max-module-lines,
                  --disable=useless-super-delegation,
                  --disable=import-error,
                  --disable=logging-fstring-interpolation,
                  --disable=invalid-name,
                  --disable=duplicate-code,
                  --disable=broad-except,
                  --disable=logging-format-interpolation,
                  --disable=too-many-lines
              ]

    -   repo: https://github.com/pycqa/flake8
        rev: 3.9.2
        hooks:
            - id: flake8
              args: [--max-line-length=120, '--ignore=E203,W503']

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.0.1
        hooks:
            - id: trailing-whitespace
